export const IPL_PLAYERS = [

  // ==================== MUMBAI INDIANS ====================
  { name: 'Rohit Sharma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 31.2, strike_rate: 130.5, economy: null, matches: 14, runs: 437, wickets: 0, image_initials: 'RS' },
  { name: 'Jasprit Bumrah', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 6.8, matches: 14, runs: 0, wickets: 22, image_initials: 'JB' },
  { name: 'Hardik Pandya', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 142.1, economy: 8.9, matches: 14, runs: 312, wickets: 12, image_initials: 'HP' },
  { name: 'Suryakumar Yadav', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 39.1, strike_rate: 168.4, economy: null, matches: 14, runs: 508, wickets: 0, image_initials: 'SKY' },
  { name: 'Tilak Varma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 148.2, economy: null, matches: 14, runs: 420, wickets: 0, image_initials: 'TV' },
  { name: 'Naman Dhir', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 22.1, strike_rate: 138.4, economy: 9.2, matches: 10, runs: 198, wickets: 6, image_initials: 'ND' },
  { name: 'Trent Boult', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.1, matches: 13, runs: 0, wickets: 18, image_initials: 'TB' },
  { name: 'Ryan Rickelton', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: null, matches: 10, runs: 324, wickets: 0, image_initials: 'RR' },
  { name: 'Will Jacks', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 158.6, economy: 8.6, matches: 10, runs: 264, wickets: 7, image_initials: 'WJ' },
  { name: 'Robin Minz', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 8, runs: 180, wickets: 0, image_initials: 'RM' },
  { name: 'Mitchell Santner', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: 7.8, matches: 8, runs: 148, wickets: 8, image_initials: 'MS' },
  { name: 'Deepak Chahar', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 10, runs: 0, wickets: 13, image_initials: 'DCh' },
  { name: 'Reece Topley', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'RT' },
  { name: 'Arjun Tendulkar', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'AT' },
  { name: 'Raj Angad Bawa', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.6, matches: 7, runs: 164, wickets: 5, image_initials: 'RAB' },
  { name: 'Karn Sharma', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 8, runs: 0, wickets: 9, image_initials: 'KSh' },
  { name: 'Mujeeb Ur Rahman', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.6, matches: 8, runs: 0, wickets: 11, image_initials: 'MUR' },
  { name: 'Vignesh Puthur', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'VP' },
  { name: 'Lizaad Williams', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'LW' },
  { name: 'Bevon Jacobs', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: null, matches: 6, runs: 148, wickets: 0, image_initials: 'BJ' },

  // ==================== CHENNAI SUPER KINGS ====================
  { name: 'MS Dhoni', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 170.2, economy: null, matches: 14, runs: 240, wickets: 0, image_initials: 'MSD' },
  { name: 'Ruturaj Gaikwad', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 41.2, strike_rate: 134.6, economy: null, matches: 14, runs: 534, wickets: 0, image_initials: 'RG' },
  { name: 'Ravindra Jadeja', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 138.9, economy: 7.8, matches: 14, runs: 310, wickets: 14, image_initials: 'RJ' },
  { name: 'Matheesha Pathirana', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.9, matches: 13, runs: 0, wickets: 20, image_initials: 'MPa' },
  { name: 'Shivam Dube', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 31.8, strike_rate: 158.4, economy: 10.2, matches: 14, runs: 382, wickets: 8, image_initials: 'ShD' },
  { name: 'Devon Conway', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 38.6, strike_rate: 132.4, economy: null, matches: 12, runs: 424, wickets: 0, image_initials: 'DC' },
  { name: 'Rachin Ravindra', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 138.6, economy: 8.4, matches: 11, runs: 304, wickets: 8, image_initials: 'RaR' },
  { name: 'Ravichandran Ashwin', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 122.6, economy: 7.4, matches: 12, runs: 148, wickets: 14, image_initials: 'RA' },
  { name: 'Sam Curran', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 22.6, strike_rate: 142.8, economy: 9.4, matches: 12, runs: 226, wickets: 11, image_initials: 'SC' },
  { name: 'Khaleel Ahmed', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 10, runs: 0, wickets: 13, image_initials: 'KA' },
  { name: 'Noor Ahmad', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 10, runs: 0, wickets: 14, image_initials: 'NA' },
  { name: 'Rahul Tripathi', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 142.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'RaT' },
  { name: 'Anshul Kamboj', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'AK' },
  { name: 'Mukesh Choudhary', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 8, runs: 0, wickets: 9, image_initials: 'MC' },
  { name: 'Vijay Shankar', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 132.6, economy: 9.4, matches: 8, runs: 180, wickets: 6, image_initials: 'VS' },
  { name: 'Shaik Rasheed', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 7, runs: 172, wickets: 0, image_initials: 'ShR' },
  { name: 'Nathan Ellis', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 8, image_initials: 'NE' },
  { name: 'Jamie Overton', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 138.6, economy: 9.6, matches: 6, runs: 110, wickets: 7, image_initials: 'JO' },
  { name: 'Deepak Hooda', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: 9.2, matches: 8, runs: 195, wickets: 5, image_initials: 'DH' },
  { name: 'Vansh Bedi', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 5, runs: 0, wickets: 6, image_initials: 'VB' },

  // ==================== ROYAL CHALLENGERS BENGALURU ====================
  { name: 'Virat Kohli', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 44.8, strike_rate: 148.2, economy: null, matches: 14, runs: 562, wickets: 0, image_initials: 'VK' },
  { name: 'Rajat Patidar', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: null, matches: 12, runs: 356, wickets: 0, image_initials: 'RPa' },
  { name: 'Faf du Plessis', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 142.8, economy: null, matches: 14, runs: 468, wickets: 0, image_initials: 'FdP' },
  { name: 'Glenn Maxwell', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 28.6, strike_rate: 162.4, economy: 8.6, matches: 12, runs: 286, wickets: 9, image_initials: 'GM' },
  { name: 'Mohammed Siraj', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 14, runs: 0, wickets: 19, image_initials: 'MSi' },
  { name: 'Yash Dayal', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.1, matches: 13, runs: 0, wickets: 14, image_initials: 'YD' },
  { name: 'Liam Livingstone', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 36.4, strike_rate: 164.8, economy: 9.2, matches: 12, runs: 380, wickets: 8, image_initials: 'LL' },
  { name: 'Phil Salt', team: 'RCB', role: 'WK-Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 158.4, economy: null, matches: 12, runs: 380, wickets: 0, image_initials: 'PS' },
  { name: 'Krunal Pandya', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 24.6, strike_rate: 138.4, economy: 8.4, matches: 12, runs: 246, wickets: 10, image_initials: 'KrP' },
  { name: 'Lungi Ngidi', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'LN' },
  { name: 'Bhuvneshwar Kumar', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 11, runs: 0, wickets: 14, image_initials: 'BK' },
  { name: 'Swapnil Singh', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: 8.2, matches: 8, runs: 148, wickets: 7, image_initials: 'SwS' },
  { name: 'Tim David', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 172.4, economy: null, matches: 10, runs: 312, wickets: 0, image_initials: 'TiD' },
  { name: 'Suyash Prabhudessai', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 8, runs: 195, wickets: 0, image_initials: 'SuP' },
  { name: 'Romario Shepherd', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.8, matches: 8, runs: 180, wickets: 7, image_initials: 'RoS' },
  { name: 'Manoj Bhandage', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 16.4, strike_rate: 132.6, economy: 8.8, matches: 7, runs: 131, wickets: 5, image_initials: 'MaB' },
  { name: 'Abhinandan Singh', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'AbS' },
  { name: 'Nuwan Thushara', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'NT' },

  // ==================== KOLKATA KNIGHT RIDERS ====================
  { name: 'Ajinkya Rahane', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 124.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'AjR' },
  { name: 'Sunil Narine', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 172.8, economy: 6.4, matches: 14, runs: 382, wickets: 16, image_initials: 'SN' },
  { name: 'Andre Russell', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 32.6, strike_rate: 178.4, economy: 9.8, matches: 13, runs: 326, wickets: 10, image_initials: 'ARu' },
  { name: 'Rinku Singh', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 162.4, economy: null, matches: 14, runs: 428, wickets: 0, image_initials: 'RiS' },
  { name: 'Varun Chakravarthy', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.2, matches: 14, runs: 0, wickets: 21, image_initials: 'VC' },
  { name: 'Quinton de Kock', team: 'KKR', role: 'WK-Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 148.6, economy: null, matches: 12, runs: 404, wickets: 0, image_initials: 'QdK' },
  { name: 'Venkatesh Iyer', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 12, runs: 256, wickets: 7, image_initials: 'VI' },
  { name: 'Anrich Nortje', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 11, runs: 0, wickets: 16, image_initials: 'AN' },
  { name: 'Harshit Rana', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 12, runs: 0, wickets: 15, image_initials: 'HR' },
  { name: 'Angkrish Raghuvanshi', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 142.6, economy: null, matches: 10, runs: 220, wickets: 0, image_initials: 'AGR' },
  { name: 'Rahmanullah Gurbaz', team: 'KKR', role: 'WK-Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 152.6, economy: null, matches: 10, runs: 324, wickets: 0, image_initials: 'RaG' },
  { name: 'Moeen Ali', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 8.4, matches: 10, runs: 202, wickets: 8, image_initials: 'MA' },
  { name: 'Spencer Johnson', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 9, runs: 0, wickets: 12, image_initials: 'SpJ' },
  { name: 'Ramandeep Singh', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 148.6, economy: 10.2, matches: 9, runs: 164, wickets: 6, image_initials: 'RmS' },
  { name: 'Manish Pandey', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 128.6, economy: null, matches: 8, runs: 228, wickets: 0, image_initials: 'MnP' },
  { name: 'Mayank Markande', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 7, runs: 0, wickets: 9, image_initials: 'MMk' },
  { name: 'Umran Malik', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 10.2, matches: 6, runs: 0, wickets: 7, image_initials: 'UM' },
  { name: 'Anukul Roy', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 16.4, strike_rate: 122.6, economy: 8.4, matches: 6, runs: 98, wickets: 6, image_initials: 'AnR' },
  { name: 'Luvnith Sisodia', team: 'KKR', role: 'WK-Batsman', base_price: 2, batting_avg: 20.4, strike_rate: 132.6, economy: null, matches: 5, runs: 102, wickets: 0, image_initials: 'LS' },

  // ==================== RAJASTHAN ROYALS ====================
  { name: 'Sanju Samson', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 152.4, economy: null, matches: 14, runs: 478, wickets: 0, image_initials: 'SaS' },
  { name: 'Jos Buttler', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 13, runs: 510, wickets: 0, image_initials: 'JBu' },
  { name: 'Yashasvi Jaiswal', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 48.4, strike_rate: 162.4, economy: null, matches: 14, runs: 580, wickets: 0, image_initials: 'YJ' },
  { name: 'Shimron Hetmyer', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 162.8, economy: null, matches: 12, runs: 346, wickets: 0, image_initials: 'SH' },
  { name: 'Riyan Parag', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 13, runs: 340, wickets: 7, image_initials: 'RPg' },
  { name: 'Jofra Archer', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 11, runs: 0, wickets: 17, image_initials: 'JA' },
  { name: 'Trent Boult', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 12, runs: 0, wickets: 15, image_initials: 'TrB' },
  { name: 'Wanindu Hasaranga', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 138.6, economy: 8.2, matches: 11, runs: 148, wickets: 12, image_initials: 'WH' },
  { name: 'Dhruv Jurel', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 138.6, economy: null, matches: 10, runs: 238, wickets: 0, image_initials: 'DJ' },
  { name: 'Yuzvendra Chahal', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 12, runs: 0, wickets: 17, image_initials: 'YC' },
  { name: 'Maheesh Theekshana', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.6, matches: 10, runs: 0, wickets: 13, image_initials: 'MT' },
  { name: 'Sandeep Sharma', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 9, runs: 0, wickets: 11, image_initials: 'SaS2' },
  { name: 'Kuldeep Sen', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'KuS' },
  { name: 'Nitish Rana', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 138.6, economy: null, matches: 8, runs: 212, wickets: 0, image_initials: 'NiR' },
  { name: 'Kumar Kartikeya', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 7, runs: 0, wickets: 9, image_initials: 'KK' },
  { name: 'Fazalhaq Farooqi', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 8, runs: 0, wickets: 11, image_initials: 'FF' },
  { name: 'Shubham Dubey', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 142.6, economy: 9.4, matches: 7, runs: 157, wickets: 5, image_initials: 'ShDu' },

  // ==================== DELHI CAPITALS ====================
  { name: 'Axar Patel', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 24.8, strike_rate: 148.4, economy: 7.6, matches: 14, runs: 298, wickets: 13, image_initials: 'AP' },
  { name: 'Kuldeep Yadav', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.4, matches: 14, runs: 0, wickets: 22, image_initials: 'KY' },
  { name: 'KL Rahul', team: 'DC', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 136.8, economy: null, matches: 14, runs: 548, wickets: 0, image_initials: 'KLR' },
  { name: 'Jake Fraser-McGurk', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 178.6, economy: null, matches: 12, runs: 404, wickets: 0, image_initials: 'JFM' },
  { name: 'Tristan Stubbs', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 158.6, economy: null, matches: 11, runs: 304, wickets: 0, image_initials: 'TS' },
  { name: 'Mitchell Starc', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 17, image_initials: 'MSta' },
  { name: 'Abishek Porel', team: 'DC', role: 'WK-Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'AbP' },
  { name: 'T Natarajan', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 15, image_initials: 'TN' },
  { name: 'Karun Nair', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 138.6, economy: null, matches: 10, runs: 280, wickets: 0, image_initials: 'KaN' },
  { name: 'Ashutosh Sharma', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.6, matches: 10, runs: 220, wickets: 6, image_initials: 'AshS' },
  { name: 'Faf du Plessis', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 142.8, economy: null, matches: 11, runs: 380, wickets: 0, image_initials: 'FdP' },
  { name: 'Sameer Rizvi', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: null, matches: 8, runs: 179, wickets: 0, image_initials: 'SaR' },
  { name: 'Mohit Sharma', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'MoS' },
  { name: 'Mukesh Kumar', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 9, runs: 0, wickets: 11, image_initials: 'MuK' },
  { name: 'Vipraj Nigam', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 7, runs: 0, wickets: 9, image_initials: 'VN' },
  { name: 'Darshan Nalkande', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'DN' },
  { name: 'Donovan Ferreira', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.6, matches: 7, runs: 157, wickets: 5, image_initials: 'DoF' },
  { name: 'Madhav Tiwari', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'MaT' },
  { name: 'Dushmantha Chameera', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 6, runs: 0, wickets: 7, image_initials: 'DuC' },

  // ==================== PUNJAB KINGS ====================
  { name: 'Shreyas Iyer', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 38.2, strike_rate: 140.6, economy: null, matches: 14, runs: 490, wickets: 0, image_initials: 'ShI' },
  { name: 'Shashank Singh', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 34.4, strike_rate: 168.6, economy: 9.8, matches: 13, runs: 378, wickets: 7, image_initials: 'ShS' },
  { name: 'Arshdeep Singh', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 14, runs: 0, wickets: 20, image_initials: 'ArS' },
  { name: 'Yuzvendra Chahal', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 14, runs: 0, wickets: 21, image_initials: 'YuC' },
  { name: 'Priyansh Arya', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 182.4, economy: null, matches: 12, runs: 400, wickets: 0, image_initials: 'PrA' },
  { name: 'Glenn Maxwell', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 28.6, strike_rate: 162.4, economy: 8.6, matches: 11, runs: 286, wickets: 7, image_initials: 'GlM' },
  { name: 'Josh Inglis', team: 'PBKS', role: 'WK-Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 152.6, economy: null, matches: 11, runs: 324, wickets: 0, image_initials: 'JI' },
  { name: 'Xavier Bartlett', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'XB' },
  { name: 'Harpreet Brar', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.6, economy: 8.4, matches: 10, runs: 148, wickets: 9, image_initials: 'HaB' },
  { name: 'Nehal Wadhera', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'NW' },
  { name: 'Harnoor Pannu', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 8, runs: 195, wickets: 0, image_initials: 'HnP' },
  { name: 'Azmatullah Omarzai', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.4, matches: 9, runs: 202, wickets: 7, image_initials: 'AO' },
  { name: 'Lockie Ferguson', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 9, runs: 0, wickets: 12, image_initials: 'LoF' },
  { name: 'Suryansh Shedge', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 148.6, economy: 9.6, matches: 7, runs: 143, wickets: 5, image_initials: 'SuS' },
  { name: 'Pyla Avinash', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'PA' },
  { name: 'Pravin Dubey', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 7, runs: 0, wickets: 9, image_initials: 'PrD' },
  { name: 'Marcus Stoinis', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: 9.6, matches: 9, runs: 256, wickets: 6, image_initials: 'MaSt' },
  { name: 'Mitchell Owen', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 172.6, economy: null, matches: 7, runs: 227, wickets: 0, image_initials: 'MiO' },

  // ==================== SUNRISERS HYDERABAD ====================
  { name: 'Heinrich Klaasen', team: 'SRH', role: 'WK-Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 178.4, economy: null, matches: 14, runs: 542, wickets: 0, image_initials: 'HK' },
  { name: 'Travis Head', team: 'SRH', role: 'Batsman', base_price: 2, batting_avg: 44.6, strike_rate: 180.2, economy: null, matches: 14, runs: 568, wickets: 0, image_initials: 'TH' },
  { name: 'Pat Cummins', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 9.2, matches: 14, runs: 224, wickets: 14, image_initials: 'PC' },
  { name: 'Abhishek Sharma', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 32.4, strike_rate: 168.4, economy: 8.6, matches: 14, runs: 390, wickets: 8, image_initials: 'AbSh' },
  { name: 'Nitish Kumar Reddy', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 13, runs: 312, wickets: 8, image_initials: 'NKR' },
  { name: 'Adam Zampa', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 11, runs: 0, wickets: 15, image_initials: 'AZ' },
  { name: 'Harshal Patel', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 12, runs: 0, wickets: 15, image_initials: 'HaP' },
  { name: 'Mohammed Shami', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 11, runs: 0, wickets: 16, image_initials: 'MSh' },
  { name: 'Ishan Kishan', team: 'SRH', role: 'WK-Batsman', base_price: 2, batting_avg: 26.8, strike_rate: 136.7, economy: null, matches: 11, runs: 295, wickets: 0, image_initials: 'IK' },
  { name: 'Zeeshan Ansari', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 8, runs: 0, wickets: 10, image_initials: 'ZA' },
  { name: 'Simarjeet Singh', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 8, image_initials: 'SiS' },
  { name: 'Atharva Taide', team: 'SRH', role: 'Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 7, runs: 157, wickets: 0, image_initials: 'ATa' },
  { name: 'Jaydev Unadkat', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 8, image_initials: 'JU' },
  { name: 'Kamindu Mendis', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 142.6, economy: 8.6, matches: 8, runs: 212, wickets: 6, image_initials: 'KaM' },
  { name: 'Wiaan Mulder', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 9.2, matches: 7, runs: 157, wickets: 6, image_initials: 'WiM' },
  { name: 'Eshan Malinga', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 5, runs: 0, wickets: 6, image_initials: 'EM' },

  // ==================== GUJARAT TITANS ====================
  { name: 'Shubman Gill', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 46.2, strike_rate: 136.4, economy: null, matches: 14, runs: 590, wickets: 0, image_initials: 'ShG' },
  { name: 'Rashid Khan', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 148.6, economy: 6.8, matches: 14, runs: 184, wickets: 20, image_initials: 'RaK' },
  { name: 'Mohammed Siraj', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 13, runs: 0, wickets: 18, image_initials: 'MoSi' },
  { name: 'Jos Buttler', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 13, runs: 510, wickets: 0, image_initials: 'JoBu' },
  { name: 'Sai Sudharsan', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 138.6, economy: null, matches: 13, runs: 460, wickets: 0, image_initials: 'SaSu' },
  { name: 'Washington Sundar', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 7.8, matches: 12, runs: 224, wickets: 12, image_initials: 'WaS' },
  { name: 'Prasidh Krishna', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 12, runs: 0, wickets: 16, image_initials: 'PrK' },
  { name: 'Kagiso Rabada', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 12, runs: 0, wickets: 17, image_initials: 'KaR' },
  { name: 'Shahrukh Khan', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 162.6, economy: null, matches: 11, runs: 264, wickets: 0, image_initials: 'ShaK' },
  { name: 'Anuj Rawat', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 9, runs: 220, wickets: 0, image_initials: 'AnRa' },
  { name: 'Rahul Tewatia', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.2, matches: 11, runs: 220, wickets: 7, image_initials: 'RaT' },
  { name: 'Gurnoor Brar', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 9, runs: 0, wickets: 11, image_initials: 'GuB' },
  { name: 'Gerald Coetzee', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 8, runs: 0, wickets: 10, image_initials: 'GeC' },
  { name: 'Glenn Phillips', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: 9.2, matches: 8, runs: 228, wickets: 6, image_initials: 'GlP' },
  { name: 'Nishant Sindhu', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.2, matches: 7, runs: 143, wickets: 5, image_initials: 'NiS' },
  { name: 'Sai Kishore', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 8, runs: 0, wickets: 10, image_initials: 'SaK' },
  { name: 'Kumar Kushagra', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 6, runs: 135, wickets: 0, image_initials: 'KuK' },
  { name: 'Manav Suthar', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 6, runs: 0, wickets: 7, image_initials: 'MaSu' },
  { name: 'Sherfane Rutherford', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 158.6, economy: null, matches: 7, runs: 185, wickets: 0, image_initials: 'ShRu' },
  { name: 'Karim Janat', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 6, runs: 122, wickets: 5, image_initials: 'KaJ' },

  // ==================== LUCKNOW SUPER GIANTS ====================
  { name: 'Rishabh Pant', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 14, runs: 548, wickets: 0, image_initials: 'RiP' },
  { name: 'Nicholas Pooran', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 164.2, economy: null, matches: 14, runs: 442, wickets: 0, image_initials: 'NiP' },
  { name: 'Ravi Bishnoi', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.6, matches: 14, runs: 0, wickets: 18, image_initials: 'RaBi' },
  { name: 'Mayank Yadav', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 11, runs: 0, wickets: 16, image_initials: 'MaY' },
  { name: 'Mitchell Marsh', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 152.6, economy: 9.4, matches: 12, runs: 304, wickets: 8, image_initials: 'MiMa' },
  { name: 'David Miller', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 38.6, strike_rate: 158.4, economy: null, matches: 12, runs: 386, wickets: 0, image_initials: 'DaM' },
  { name: 'Aiden Markram', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: 8.6, matches: 12, runs: 324, wickets: 7, image_initials: 'AiM' },
  { name: 'Avesh Khan', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 15, image_initials: 'AvK' },
  { name: 'Ayush Badoni', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 11, runs: 284, wickets: 0, image_initials: 'AyB' },
  { name: 'Akash Deep', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'AkD' },
  { name: 'Shahbaz Ahmed', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 8.6, matches: 10, runs: 202, wickets: 8, image_initials: 'ShAh' },
  { name: 'Abdul Samad', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.8, matches: 9, runs: 220, wickets: 5, image_initials: 'AbSa' },
  { name: 'Matthew Breetzke', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 8, runs: 227, wickets: 0, image_initials: 'MaBr' },
  { name: 'Shamar Joseph', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 8, runs: 0, wickets: 10, image_initials: 'ShJ' },
  { name: 'Arshin Kulkarni', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 7, runs: 143, wickets: 5, image_initials: 'ArK' },
  { name: 'Manimaran Siddharth', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 7, runs: 0, wickets: 9, image_initials: 'MaSi' },
  { name: 'Himmat Singh', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: null, matches: 6, runs: 147, wickets: 0, image_initials: 'HiS' },
  { name: 'Aryan Juyal', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: null, matches: 5, runs: 92, wickets: 0, image_initials: 'ArJ' },
  { name: 'Digvesh Singh', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'DiS' },
  { name: 'Prince Yadav', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 4, runs: 0, wickets: 5, image_initials: 'PrY' },
]

export const TEAM_COLORS = {
  MI: { bg: '#004BA0', text: '#FFFFFF', accent: '#00BFFF' },
  CSK: { bg: '#F5A623', text: '#0B1E3D', accent: '#FDD835' },
  RCB: { bg: '#C8102E', text: '#FFFFFF', accent: '#FFD700' },
  KKR: { bg: '#3A225D', text: '#FFD700', accent: '#FFD700' },
  RR: { bg: '#EA1A85', text: '#FFFFFF', accent: '#29ABE2' },
  DC: { bg: '#0078BC', text: '#FFFFFF', accent: '#EF1C25' },
  PBKS: { bg: '#ED1B24', text: '#FFFFFF', accent: '#A7A9AC' },
  SRH: { bg: '#FF822A', text: '#FFFFFF', accent: '#000000' },
  GT: { bg: '#1C1C5E', text: '#FFFFFF', accent: '#0ABFBC' },
  LSG: { bg: '#A72056', text: '#FFFFFF', accent: '#00B4D8' },
}