export const IPL_PLAYERS = [

  // ==================== ROYAL CHALLENGERS BENGALURU ====================
  { name: 'Rajat Patidar', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: null, matches: 12, runs: 356, wickets: 0, image_initials: 'RPa' },
  { name: 'Virat Kohli', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 44.8, strike_rate: 148.2, economy: null, matches: 14, runs: 562, wickets: 0, image_initials: 'VK' },
  { name: 'Devdutt Padikkal', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 132.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'DP' },
  { name: 'Jitesh Sharma', team: 'RCB', role: 'WK-Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 152.6, economy: null, matches: 10, runs: 238, wickets: 0, image_initials: 'JiS' },
  { name: 'Krunal Pandya', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 24.6, strike_rate: 138.4, economy: 8.4, matches: 12, runs: 246, wickets: 10, image_initials: 'KrP' },
  { name: 'Swapnil Singh', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: 8.2, matches: 8, runs: 148, wickets: 7, image_initials: 'SwS' },
  { name: 'Bhuvneshwar Kumar', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 11, runs: 0, wickets: 14, image_initials: 'BK' },
  { name: 'Rasikh Salam', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'RaS' },
  { name: 'Yash Dayal', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.1, matches: 13, runs: 0, wickets: 14, image_initials: 'YD' },
  { name: 'Suyash Sharma', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 8, runs: 0, wickets: 10, image_initials: 'SuSh' },
  { name: 'Abhinandan Singh', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'AbS' },
  { name: 'Venkatesh Iyer', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 12, runs: 256, wickets: 7, image_initials: 'VI' },
  { name: 'Mangesh Yadav', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 7, runs: 0, wickets: 9, image_initials: 'MaY' },
  { name: 'Satvik Deswal', team: 'RCB', role: 'WK-Batsman', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: null, matches: 5, runs: 92, wickets: 0, image_initials: 'SaD' },
  { name: 'Vicky Ostwal', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 7, runs: 0, wickets: 9, image_initials: 'VO' },
  { name: 'Tim David', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 172.4, economy: null, matches: 10, runs: 312, wickets: 0, image_initials: 'TiD' },
  { name: 'Phil Salt', team: 'RCB', role: 'WK-Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 158.4, economy: null, matches: 12, runs: 380, wickets: 0, image_initials: 'PhS' },
  { name: 'Jacob Bethell', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 148.6, economy: 8.8, matches: 8, runs: 211, wickets: 6, image_initials: 'JaBe' },
  { name: 'Romario Shepherd', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.8, matches: 8, runs: 180, wickets: 7, image_initials: 'RoSh' },
  { name: 'Josh Hazlewood', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 9, runs: 0, wickets: 12, image_initials: 'JoH' },
  { name: 'Nuwan Thushara', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'NuT' },
  { name: 'Jacob Duffy', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 6, runs: 0, wickets: 7, image_initials: 'JaDu' },
  { name: 'Jordan Cox', team: 'RCB', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 6, runs: 135, wickets: 0, image_initials: 'JoCo' },
  { name: 'Kanishk Chouhan', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'KaCh' },
  { name: 'Vihaan Malhotra', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: null, matches: 4, runs: 74, wickets: 0, image_initials: 'ViM' },

  // ==================== CHENNAI SUPER KINGS ====================
  { name: 'Ruturaj Gaikwad', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 41.2, strike_rate: 134.6, economy: null, matches: 14, runs: 534, wickets: 0, image_initials: 'RG' },
  { name: 'MS Dhoni', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 170.2, economy: null, matches: 14, runs: 240, wickets: 0, image_initials: 'MSD' },
  { name: 'Sanju Samson', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 152.4, economy: null, matches: 14, runs: 478, wickets: 0, image_initials: 'SaS' },
  { name: 'Ayush Mhatre', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 9, runs: 256, wickets: 0, image_initials: 'AyM' },
  { name: 'Urvil Patel', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 162.6, economy: null, matches: 8, runs: 211, wickets: 0, image_initials: 'UrP' },
  { name: 'Shivam Dube', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 31.8, strike_rate: 158.4, economy: 10.2, matches: 14, runs: 382, wickets: 8, image_initials: 'ShD' },
  { name: 'Anshul Kamboj', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'AnK' },
  { name: 'Ramakrishna Ghosh', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.6, economy: 9.2, matches: 7, runs: 130, wickets: 6, image_initials: 'RKG' },
  { name: 'Khaleel Ahmed', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 10, runs: 0, wickets: 13, image_initials: 'KhA' },
  { name: 'Mukesh Choudhary', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 8, runs: 0, wickets: 9, image_initials: 'MuC' },
  { name: 'Shreyas Gopal', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 9, runs: 0, wickets: 11, image_initials: 'ShG' },
  { name: 'Gurjapneet Singh', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 6, runs: 0, wickets: 7, image_initials: 'GuS' },
  { name: 'Prashant Veer', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 9, image_initials: 'PrV' },
  { name: 'Kartik Sharma', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 7, runs: 143, wickets: 5, image_initials: 'KaS' },
  { name: 'Sarfaraz Khan', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 142.6, economy: null, matches: 8, runs: 228, wickets: 0, image_initials: 'SarK' },
  { name: 'Rahul Chahar', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 8, runs: 0, wickets: 10, image_initials: 'RaCh' },
  { name: 'Dewald Brevis', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 24.2, strike_rate: 152.4, economy: null, matches: 10, runs: 242, wickets: 0, image_initials: 'DeB' },
  { name: 'Jamie Overton', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 138.6, economy: 9.6, matches: 6, runs: 110, wickets: 7, image_initials: 'JaO' },
  { name: 'Noor Ahmad', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 10, runs: 0, wickets: 14, image_initials: 'NoA' },
  { name: 'Nathan Ellis', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 8, image_initials: 'NaE' },
  { name: 'Akeal Hosein', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 7, runs: 0, wickets: 9, image_initials: 'AkH' },
  { name: 'Matthew Short', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: 9.2, matches: 7, runs: 171, wickets: 5, image_initials: 'MaSh' },
  { name: 'Matt Henry', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 6, runs: 0, wickets: 8, image_initials: 'MaHe' },
  { name: 'Zak Foulkes', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 5, runs: 0, wickets: 6, image_initials: 'ZaF' },
  { name: 'Aman Khan', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'AmK' },

  // ==================== KOLKATA KNIGHT RIDERS ====================
  { name: 'Ajinkya Rahane', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 124.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'AjR' },
  { name: 'Rinku Singh', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 162.4, economy: null, matches: 14, runs: 428, wickets: 0, image_initials: 'RiS' },
  { name: 'Angkrish Raghuvanshi', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 142.6, economy: null, matches: 10, runs: 220, wickets: 0, image_initials: 'AnRa' },
  { name: 'Manish Pandey', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 128.6, economy: null, matches: 8, runs: 228, wickets: 0, image_initials: 'MnP' },
  { name: 'Anukul Roy', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 16.4, strike_rate: 122.6, economy: 8.4, matches: 6, runs: 98, wickets: 6, image_initials: 'AnR' },
  { name: 'Ramandeep Singh', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 148.6, economy: 10.2, matches: 9, runs: 164, wickets: 6, image_initials: 'RmS' },
  { name: 'Vaibhav Arora', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 9, runs: 0, wickets: 12, image_initials: 'VaA' },
  { name: 'Varun Chakravarthy', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.2, matches: 14, runs: 0, wickets: 21, image_initials: 'VaC' },
  { name: 'Harshit Rana', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 12, runs: 0, wickets: 15, image_initials: 'HaR' },
  { name: 'Umran Malik', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 10.2, matches: 6, runs: 0, wickets: 7, image_initials: 'UmM' },
  { name: 'Rahul Tripathi', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 142.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'RaTr' },
  { name: 'Akash Deep', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'AkD' },
  { name: 'Tejasvi Singh', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 7, runs: 143, wickets: 5, image_initials: 'TeS' },
  { name: 'Sunil Narine', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 172.8, economy: 6.4, matches: 14, runs: 382, wickets: 16, image_initials: 'SuN' },
  { name: 'Cameron Green', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 158.6, economy: 9.4, matches: 11, runs: 304, wickets: 8, image_initials: 'CaG' },
  { name: 'Matheesha Pathirana', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.9, matches: 13, runs: 0, wickets: 20, image_initials: 'MaPa' },
  { name: 'Rovman Powell', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 158.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'RoP' },
  { name: 'Finn Allen', team: 'KKR', role: 'WK-Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 162.6, economy: null, matches: 9, runs: 228, wickets: 0, image_initials: 'FiA' },
  { name: 'Rachin Ravindra', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 138.6, economy: 8.4, matches: 11, runs: 304, wickets: 8, image_initials: 'RaRa' },
  { name: 'Tim Seifert', team: 'KKR', role: 'WK-Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: null, matches: 7, runs: 171, wickets: 0, image_initials: 'TiSe' },
  { name: 'Blessing Muzarabani', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'BlM' },
  { name: 'Daksh Kamra', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'DaK' },
  { name: 'Prashant Solanki', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 4, runs: 0, wickets: 5, image_initials: 'PrSo' },
  { name: 'Kartik Tyagi', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 4, runs: 0, wickets: 5, image_initials: 'KaTy' },
  { name: 'Sarthak Ranjan', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 3, runs: 0, wickets: 4, image_initials: 'SaRa' },

  // ==================== MUMBAI INDIANS ====================
  { name: 'Rohit Sharma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 31.2, strike_rate: 130.5, economy: null, matches: 14, runs: 437, wickets: 0, image_initials: 'RoS' },
  { name: 'Suryakumar Yadav', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 39.1, strike_rate: 168.4, economy: null, matches: 14, runs: 508, wickets: 0, image_initials: 'SKY' },
  { name: 'Tilak Varma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 148.2, economy: null, matches: 14, runs: 420, wickets: 0, image_initials: 'TiV' },
  { name: 'Hardik Pandya', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 142.1, economy: 8.9, matches: 14, runs: 312, wickets: 12, image_initials: 'HaP' },
  { name: 'Jasprit Bumrah', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 6.8, matches: 14, runs: 0, wickets: 22, image_initials: 'JaB' },
  { name: 'Naman Dhir', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 22.1, strike_rate: 138.4, economy: 9.2, matches: 10, runs: 198, wickets: 6, image_initials: 'NaD' },
  { name: 'Robin Minz', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 8, runs: 180, wickets: 0, image_initials: 'RoM' },
  { name: 'Raj Bawa', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.6, matches: 7, runs: 164, wickets: 5, image_initials: 'RaB' },
  { name: 'Deepak Chahar', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 10, runs: 0, wickets: 13, image_initials: 'DeC' },
  { name: 'Ashwani Kumar', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'AsK' },
  { name: 'Shardul Thakur', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.4, economy: 9.8, matches: 10, runs: 148, wickets: 10, image_initials: 'ShT' },
  { name: 'Mayank Markande', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 7, runs: 0, wickets: 9, image_initials: 'MaMa' },
  { name: 'Atharva Ankolekar', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 16.4, strike_rate: 122.6, economy: 8.6, matches: 6, runs: 98, wickets: 6, image_initials: 'AtA' },
  { name: 'Ryan Rickelton', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: null, matches: 10, runs: 324, wickets: 0, image_initials: 'RyR' },
  { name: 'Mitchell Santner', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: 7.8, matches: 8, runs: 148, wickets: 8, image_initials: 'MiSa' },
  { name: 'Will Jacks', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 158.6, economy: 8.6, matches: 10, runs: 264, wickets: 7, image_initials: 'WiJ' },
  { name: 'Corbin Bosch', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 142.6, economy: 9.4, matches: 7, runs: 157, wickets: 6, image_initials: 'CoB' },
  { name: 'Trent Boult', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.1, matches: 13, runs: 0, wickets: 18, image_initials: 'TrB' },
  { name: 'Allah Ghazanfar', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 8, runs: 0, wickets: 11, image_initials: 'AlG' },
  { name: 'Sherfane Rutherford', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 158.6, economy: null, matches: 7, runs: 185, wickets: 0, image_initials: 'ShRu' },
  { name: 'Quinton de Kock', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 148.6, economy: null, matches: 12, runs: 404, wickets: 0, image_initials: 'QdK' },
  { name: 'Raghu Sharma', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'RaSh' },

  // ==================== SUNRISERS HYDERABAD ====================
  { name: 'Abhishek Sharma', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 32.4, strike_rate: 168.4, economy: 8.6, matches: 14, runs: 390, wickets: 8, image_initials: 'AbSh' },
  { name: 'Ishan Kishan', team: 'SRH', role: 'WK-Batsman', base_price: 2, batting_avg: 26.8, strike_rate: 136.7, economy: null, matches: 11, runs: 295, wickets: 0, image_initials: 'IsK' },
  { name: 'Nitish Kumar Reddy', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 13, runs: 312, wickets: 8, image_initials: 'NKR' },
  { name: 'Harshal Patel', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 12, runs: 0, wickets: 15, image_initials: 'HaPa' },
  { name: 'Jaydev Unadkat', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 8, image_initials: 'JaU' },
  { name: 'Zeeshan Ansari', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 8, runs: 0, wickets: 10, image_initials: 'ZeA' },
  { name: 'Aniket Verma', team: 'SRH', role: 'Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 7, runs: 157, wickets: 0, image_initials: 'AnV' },
  { name: 'Harsh Dubey', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 7, runs: 0, wickets: 9, image_initials: 'HaDu' },
  { name: 'Shivam Mavi', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 8, runs: 0, wickets: 10, image_initials: 'ShMa' },
  { name: 'Travis Head', team: 'SRH', role: 'Batsman', base_price: 2, batting_avg: 44.6, strike_rate: 180.2, economy: null, matches: 14, runs: 568, wickets: 0, image_initials: 'TrH' },
  { name: 'Heinrich Klaasen', team: 'SRH', role: 'WK-Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 178.4, economy: null, matches: 14, runs: 542, wickets: 0, image_initials: 'HeK' },
  { name: 'Kamindu Mendis', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 142.6, economy: 8.6, matches: 8, runs: 212, wickets: 6, image_initials: 'KaMe' },
  { name: 'Brydon Carse', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 148.6, economy: 9.4, matches: 8, runs: 163, wickets: 7, image_initials: 'BrC' },
  { name: 'Pat Cummins', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 9.2, matches: 14, runs: 224, wickets: 14, image_initials: 'PaCu' },
  { name: 'Liam Livingstone', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 36.4, strike_rate: 164.8, economy: 9.2, matches: 12, runs: 380, wickets: 8, image_initials: 'LiL' },
  { name: 'Eshan Malinga', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 5, runs: 0, wickets: 6, image_initials: 'EsM' },
  { name: 'Jack Edwards', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 6, runs: 122, wickets: 5, image_initials: 'JaE' },

  // ==================== RAJASTHAN ROYALS ====================
  { name: 'Yashasvi Jaiswal', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 48.4, strike_rate: 162.4, economy: null, matches: 14, runs: 580, wickets: 0, image_initials: 'YaJ' },
  { name: 'Dhruv Jurel', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 138.6, economy: null, matches: 10, runs: 238, wickets: 0, image_initials: 'DhJ' },
  { name: 'Riyan Parag', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: 9.4, matches: 13, runs: 340, wickets: 7, image_initials: 'RiP' },
  { name: 'Shubham Dubey', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 142.6, economy: 9.4, matches: 7, runs: 157, wickets: 5, image_initials: 'ShDu' },
  { name: 'Vaibhav Suryavanshi', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 168.6, economy: null, matches: 9, runs: 274, wickets: 0, image_initials: 'VaSu' },
  { name: 'Ravindra Jadeja', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 138.9, economy: 7.8, matches: 14, runs: 310, wickets: 14, image_initials: 'RaJ' },
  { name: 'Ravi Bishnoi', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.6, matches: 14, runs: 0, wickets: 18, image_initials: 'RaBi' },
  { name: 'Sandeep Sharma', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 9, runs: 0, wickets: 11, image_initials: 'SaSh' },
  { name: 'Tushar Deshpande', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 10, runs: 0, wickets: 12, image_initials: 'TuD' },
  { name: 'Kuldeep Sen', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'KuSe' },
  { name: 'Yudhvir Singh Charak', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 7, runs: 0, wickets: 9, image_initials: 'YuC' },
  { name: 'Lhuan-dre Pretorius', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 158.6, economy: null, matches: 8, runs: 228, wickets: 0, image_initials: 'LhP' },
  { name: 'Shimron Hetmyer', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 162.8, economy: null, matches: 12, runs: 346, wickets: 0, image_initials: 'ShHe' },
  { name: 'Jofra Archer', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 11, runs: 0, wickets: 17, image_initials: 'JoA' },
  { name: 'Kwena Maphaka', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'KwM' },
  { name: 'Nandre Burger', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 7, runs: 0, wickets: 9, image_initials: 'NaBu' },
  { name: 'Sam Curran', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 22.6, strike_rate: 142.8, economy: 9.4, matches: 12, runs: 226, wickets: 11, image_initials: 'SaCu' },
  { name: 'Donovan Ferreira', team: 'RR', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.6, matches: 7, runs: 157, wickets: 5, image_initials: 'DoF' },
  { name: 'Adam Milne', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 6, runs: 0, wickets: 7, image_initials: 'AdM' },

  // ==================== DELHI CAPITALS ====================
  { name: 'KL Rahul', team: 'DC', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 136.8, economy: null, matches: 14, runs: 548, wickets: 0, image_initials: 'KLR' },
  { name: 'Axar Patel', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 24.8, strike_rate: 148.4, economy: 7.6, matches: 14, runs: 298, wickets: 13, image_initials: 'AxP' },
  { name: 'Kuldeep Yadav', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.4, matches: 14, runs: 0, wickets: 22, image_initials: 'KuY' },
  { name: 'Karun Nair', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 138.6, economy: null, matches: 10, runs: 280, wickets: 0, image_initials: 'KaN' },
  { name: 'Abishek Porel', team: 'DC', role: 'WK-Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'AbP' },
  { name: 'Sameer Rizvi', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: null, matches: 8, runs: 179, wickets: 0, image_initials: 'SaRi' },
  { name: 'Ashutosh Sharma', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.6, matches: 10, runs: 220, wickets: 6, image_initials: 'AsSh' },
  { name: 'T Natarajan', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 15, image_initials: 'TNa' },
  { name: 'Mukesh Kumar', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 9, runs: 0, wickets: 11, image_initials: 'MuKu' },
  { name: 'Vipraj Nigam', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 7, runs: 0, wickets: 9, image_initials: 'ViN' },
  { name: 'Nitish Rana', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 138.6, economy: null, matches: 8, runs: 212, wickets: 0, image_initials: 'NiRa' },
  { name: 'Prithvi Shaw', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 158.6, economy: null, matches: 10, runs: 324, wickets: 0, image_initials: 'PrSh' },
  { name: 'Madhav Tiwari', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'MaTi' },
  { name: 'Tristan Stubbs', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 158.6, economy: null, matches: 11, runs: 304, wickets: 0, image_initials: 'TrSt' },
  { name: 'Mitchell Starc', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 17, image_initials: 'MiSt' },
  { name: 'Dushmantha Chameera', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.6, matches: 6, runs: 0, wickets: 7, image_initials: 'DuC' },
  { name: 'Ben Duckett', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 152.6, economy: null, matches: 10, runs: 364, wickets: 0, image_initials: 'BeD' },
  { name: 'David Miller', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 38.6, strike_rate: 158.4, economy: null, matches: 12, runs: 386, wickets: 0, image_initials: 'DaM' },
  { name: 'Pathum Nissanka', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 30.4, strike_rate: 138.6, economy: null, matches: 9, runs: 274, wickets: 0, image_initials: 'PaN' },
  { name: 'Lungi Ngidi', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'LuN' },
  { name: 'Kyle Jamieson', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.6, economy: 9.2, matches: 8, runs: 148, wickets: 8, image_initials: 'KyJ' },

  // ==================== PUNJAB KINGS ====================
  { name: 'Shreyas Iyer', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 38.2, strike_rate: 140.6, economy: null, matches: 14, runs: 490, wickets: 0, image_initials: 'ShIy' },
  { name: 'Shashank Singh', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 34.4, strike_rate: 168.6, economy: 9.8, matches: 13, runs: 378, wickets: 7, image_initials: 'ShSi' },
  { name: 'Arshdeep Singh', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 14, runs: 0, wickets: 20, image_initials: 'ArS' },
  { name: 'Yuzvendra Chahal', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 14, runs: 0, wickets: 21, image_initials: 'YuCh' },
  { name: 'Priyansh Arya', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 182.4, economy: null, matches: 12, runs: 400, wickets: 0, image_initials: 'PrAr' },
  { name: 'Prabhsimran Singh', team: 'PBKS', role: 'WK-Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'PrSi' },
  { name: 'Nehal Wadhera', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: null, matches: 10, runs: 256, wickets: 0, image_initials: 'NeW' },
  { name: 'Harpreet Brar', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.6, economy: 8.4, matches: 10, runs: 148, wickets: 9, image_initials: 'HaBr' },
  { name: 'Harnoor Pannu', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 8, runs: 195, wickets: 0, image_initials: 'HaPa' },
  { name: 'Musheer Khan', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 142.6, economy: null, matches: 9, runs: 256, wickets: 0, image_initials: 'MuKh' },
  { name: 'Suryansh Shedge', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 148.6, economy: 9.6, matches: 7, runs: 143, wickets: 5, image_initials: 'SuSh' },
  { name: 'Vyshak Vijaykumar', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 9, runs: 0, wickets: 12, image_initials: 'VyV' },
  { name: 'Pravin Dubey', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 7, runs: 0, wickets: 9, image_initials: 'PrDu' },
  { name: 'Pyla Avinash', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'PyA' },
  { name: 'Yash Thakur', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 7, runs: 0, wickets: 9, image_initials: 'YaTh' },
  { name: 'Marcus Stoinis', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: 9.6, matches: 9, runs: 256, wickets: 6, image_initials: 'MaSto' },
  { name: 'Marco Jansen', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.2, matches: 9, runs: 164, wickets: 8, image_initials: 'MaJa' },
  { name: 'Azmatullah Omarzai', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 148.6, economy: 9.4, matches: 9, runs: 202, wickets: 7, image_initials: 'AzO' },
  { name: 'Mitch Owen', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 172.6, economy: null, matches: 7, runs: 227, wickets: 0, image_initials: 'MiOw' },
  { name: 'Xavier Bartlett', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 10, runs: 0, wickets: 13, image_initials: 'XaB' },
  { name: 'Lockie Ferguson', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 9, runs: 0, wickets: 12, image_initials: 'LoF' },
  { name: 'Cooper Connolly', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 7, runs: 143, wickets: 5, image_initials: 'CoC' },
  { name: 'Ben Dwarshuis', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'BeDw' },
  { name: 'Vishnu Vinod', team: 'PBKS', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 6, runs: 135, wickets: 0, image_initials: 'ViVi' },
  { name: 'Vishal Nishad', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'ViNi' },

  // ==================== LUCKNOW SUPER GIANTS ====================
  { name: 'Rishabh Pant', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 14, runs: 548, wickets: 0, image_initials: 'RiPa' },
  { name: 'Ayush Badoni', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 11, runs: 284, wickets: 0, image_initials: 'AyB' },
  { name: 'Abdul Samad', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.8, matches: 9, runs: 220, wickets: 5, image_initials: 'AbSa' },
  { name: 'Himmat Singh', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 148.6, economy: null, matches: 6, runs: 147, wickets: 0, image_initials: 'HiS' },
  { name: 'Shahbaz Ahmed', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 8.6, matches: 10, runs: 202, wickets: 8, image_initials: 'ShAh' },
  { name: 'Arshin Kulkarni', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.4, matches: 7, runs: 143, wickets: 5, image_initials: 'ArKu' },
  { name: 'Mayank Yadav', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 11, runs: 0, wickets: 16, image_initials: 'MaYa' },
  { name: 'Avesh Khan', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 15, image_initials: 'AvK' },
  { name: 'Mohsin Khan', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 9, runs: 0, wickets: 12, image_initials: 'MoK' },
  { name: 'Manimaran Siddharth', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 7, runs: 0, wickets: 9, image_initials: 'MaSi' },
  { name: 'Digvesh Rathi', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 5, runs: 0, wickets: 6, image_initials: 'DiR' },
  { name: 'Akash Singh', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 5, runs: 0, wickets: 6, image_initials: 'AkSi' },
  { name: 'Arjun Tendulkar', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'ArT' },
  { name: 'Mohammed Shami', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 13, runs: 0, wickets: 19, image_initials: 'MoSh' },
  { name: 'Mitchell Marsh', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 152.6, economy: 9.4, matches: 12, runs: 304, wickets: 8, image_initials: 'MiMa' },
  { name: 'Aiden Markram', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 32.4, strike_rate: 148.6, economy: 8.6, matches: 12, runs: 324, wickets: 7, image_initials: 'AiMa' },
  { name: 'Nicholas Pooran', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 164.2, economy: null, matches: 14, runs: 442, wickets: 0, image_initials: 'NiPo' },
  { name: 'Anrich Nortje', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 11, runs: 0, wickets: 16, image_initials: 'AnNo' },
  { name: 'Wanindu Hasaranga', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 138.6, economy: 8.2, matches: 11, runs: 148, wickets: 12, image_initials: 'WaH' },
  { name: 'Josh Inglis', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 32.4, strike_rate: 152.6, economy: null, matches: 11, runs: 324, wickets: 0, image_initials: 'JoIn' },
  { name: 'Matthew Breetzke', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 28.4, strike_rate: 148.6, economy: null, matches: 8, runs: 227, wickets: 0, image_initials: 'MaBr' },
  { name: 'Prince Yadav', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 4, runs: 0, wickets: 5, image_initials: 'PrYa' },
  { name: 'Naman Tiwari', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'NaTi' },
  { name: 'Akshat Raghuwanshi', team: 'LSG', role: 'Batsman', base_price: 2, batting_avg: 18.4, strike_rate: 128.6, economy: null, matches: 4, runs: 74, wickets: 0, image_initials: 'AkRa' },
  { name: 'Mukul Choudhary', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 4, runs: 0, wickets: 5, image_initials: 'MuCh' },

  // ==================== GUJARAT TITANS ====================
  { name: 'Shubman Gill', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 46.2, strike_rate: 136.4, economy: null, matches: 14, runs: 590, wickets: 0, image_initials: 'ShGi' },
  { name: 'Sai Sudharsan', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 138.6, economy: null, matches: 13, runs: 460, wickets: 0, image_initials: 'SaSu' },
  { name: 'Kumar Kushagra', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: null, matches: 6, runs: 135, wickets: 0, image_initials: 'KuKu' },
  { name: 'Anuj Rawat', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 24.4, strike_rate: 138.6, economy: null, matches: 9, runs: 220, wickets: 0, image_initials: 'AnRaw' },
  { name: 'Nishant Sindhu', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 20.4, strike_rate: 138.6, economy: 9.2, matches: 7, runs: 143, wickets: 5, image_initials: 'NiSi' },
  { name: 'Washington Sundar', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 7.8, matches: 12, runs: 224, wickets: 12, image_initials: 'WaSu' },
  { name: 'Arshad Khan', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 8, runs: 0, wickets: 10, image_initials: 'ArKh' },
  { name: 'Shahrukh Khan', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 162.6, economy: null, matches: 11, runs: 264, wickets: 0, image_initials: 'ShKh' },
  { name: 'Rahul Tewatia', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 24.4, strike_rate: 158.6, economy: 9.2, matches: 11, runs: 220, wickets: 7, image_initials: 'RaTe' },
  { name: 'Mohammed Siraj', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 13, runs: 0, wickets: 18, image_initials: 'MoSi' },
  { name: 'Prasidh Krishna', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 12, runs: 0, wickets: 16, image_initials: 'PrKr' },
  { name: 'Gurnoor Singh Brar', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 9, runs: 0, wickets: 11, image_initials: 'GuBr' },
  { name: 'Manav Suthar', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 6, runs: 0, wickets: 7, image_initials: 'MaSut' },
  { name: 'Sai Kishore', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 8, runs: 0, wickets: 10, image_initials: 'SaKi' },
  { name: 'Jayant Yadav', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 122.6, economy: 8.4, matches: 7, runs: 128, wickets: 7, image_initials: 'JaYa' },
  { name: 'Ishant Sharma', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'IsSh' },
  { name: 'Prithviraj Yarra', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'PrYar' },
  { name: 'Ashok Sharma', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 4, runs: 0, wickets: 5, image_initials: 'AshSh' },
  { name: 'Jos Buttler', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 13, runs: 510, wickets: 0, image_initials: 'JoBu' },
  { name: 'Glenn Phillips', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 152.6, economy: 9.2, matches: 8, runs: 228, wickets: 6, image_initials: 'GlPh' },
  { name: 'Kagiso Rabada', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 12, runs: 0, wickets: 17, image_initials: 'KaRa' },
  { name: 'Rashid Khan', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 148.6, economy: 6.8, matches: 14, runs: 184, wickets: 20, image_initials: 'RaKh' },
  { name: 'Jason Holder', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 132.6, economy: 9.2, matches: 8, runs: 148, wickets: 8, image_initials: 'JaHo' },
  { name: 'Tom Banton', team: 'GT', role: 'WK-Batsman', base_price: 2, batting_avg: 26.4, strike_rate: 152.6, economy: null, matches: 7, runs: 185, wickets: 0, image_initials: 'ToBa' },
  { name: 'Luke Wood', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 6, runs: 0, wickets: 7, image_initials: 'LuW' },
]

export const TEAM_COLORS = {
  MI: { bg: '#004BA0', text: '#FFFFFF', accent: '#00BFFF' },
  CSK: { bg: '#F5A623', text: '#0B1E3D', accent: '#FDD835' },
  RCB: { bg: '#C8102E', text: '#FFFFFF', accent: '#FFD700' },
  KKR: { bg: '#3A225D', text: '#FFD700', accent: '#FFD700' },
  RR: { bg: '#EA1A85', text: '#FFFFFF', accent: '#29ABE2' },
  DC: { bg: '#0078BC', text: '#FFFFFF', accent: '#EF1C25' },
  PBKS: { bg: '#ED1B24', text: '#FFFFFF', accent: '#A7A9AC' },
  SRH: { bg: '#FF822A', text: '#FFFFFF', accent: '#000000' },
  GT: { bg: '#1C1C5E', text: '#FFFFFF', accent: '#0ABFBC' },
  LSG: { bg: '#A72056', text: '#FFFFFF', accent: '#00B4D8' },
}