export const IPL_PLAYERS = [
  { name: 'Rohit Sharma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 31.2, strike_rate: 130.5, economy: null, matches: 14, runs: 437, wickets: 0, image_initials: 'RS' },
  { name: 'Jasprit Bumrah', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 6.8, matches: 14, runs: 0, wickets: 22, image_initials: 'JB' },
  { name: 'Hardik Pandya', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 28.4, strike_rate: 142.1, economy: 8.9, matches: 14, runs: 312, wickets: 12, image_initials: 'HP' },
  { name: 'Suryakumar Yadav', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 39.1, strike_rate: 168.4, economy: null, matches: 14, runs: 508, wickets: 0, image_initials: 'SY' },
  { name: 'Tilak Varma', team: 'MI', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 148.2, economy: null, matches: 14, runs: 420, wickets: 0, image_initials: 'TV' },
  { name: 'Ishan Kishan', team: 'MI', role: 'WK-Batsman', base_price: 2, batting_avg: 26.8, strike_rate: 136.7, economy: null, matches: 13, runs: 348, wickets: 0, image_initials: 'IK' },
  { name: 'Naman Dhir', team: 'MI', role: 'All-Rounder', base_price: 2, batting_avg: 22.1, strike_rate: 138.4, economy: 9.2, matches: 10, runs: 198, wickets: 6, image_initials: 'ND' },
  { name: 'Trent Boult', team: 'MI', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.1, matches: 13, runs: 0, wickets: 18, image_initials: 'TB' },
  { name: 'MS Dhoni', team: 'CSK', role: 'WK-Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 170.2, economy: null, matches: 14, runs: 240, wickets: 0, image_initials: 'MD' },
  { name: 'Ruturaj Gaikwad', team: 'CSK', role: 'Batsman', base_price: 2, batting_avg: 41.2, strike_rate: 134.6, economy: null, matches: 14, runs: 534, wickets: 0, image_initials: 'RG' },
  { name: 'Ravindra Jadeja', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 26.4, strike_rate: 138.9, economy: 7.8, matches: 14, runs: 310, wickets: 14, image_initials: 'RJ' },
  { name: 'Deepak Chahar', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 12, runs: 0, wickets: 15, image_initials: 'DC' },
  { name: 'Shivam Dube', team: 'CSK', role: 'All-Rounder', base_price: 2, batting_avg: 31.8, strike_rate: 158.4, economy: 10.2, matches: 14, runs: 382, wickets: 8, image_initials: 'SD' },
  { name: 'Matheesha Pathirana', team: 'CSK', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.9, matches: 13, runs: 0, wickets: 20, image_initials: 'MPa' },
  { name: 'Virat Kohli', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 44.8, strike_rate: 148.2, economy: null, matches: 14, runs: 562, wickets: 0, image_initials: 'VK' },
  { name: 'Faf du Plessis', team: 'RCB', role: 'Batsman', base_price: 2, batting_avg: 36.4, strike_rate: 142.8, economy: null, matches: 14, runs: 468, wickets: 0, image_initials: 'FD' },
  { name: 'Glenn Maxwell', team: 'RCB', role: 'All-Rounder', base_price: 2, batting_avg: 28.6, strike_rate: 162.4, economy: 8.6, matches: 12, runs: 286, wickets: 9, image_initials: 'GM' },
  { name: 'Mohammed Siraj', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 14, runs: 0, wickets: 19, image_initials: 'MSi' },
  { name: 'Yash Dayal', team: 'RCB', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.1, matches: 13, runs: 0, wickets: 14, image_initials: 'YD' },
  { name: 'Shreyas Iyer', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 38.2, strike_rate: 140.6, economy: null, matches: 14, runs: 490, wickets: 0, image_initials: 'SI' },
  { name: 'Sunil Narine', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 30.4, strike_rate: 172.8, economy: 6.4, matches: 14, runs: 382, wickets: 16, image_initials: 'SN' },
  { name: 'Andre Russell', team: 'KKR', role: 'All-Rounder', base_price: 2, batting_avg: 32.6, strike_rate: 178.4, economy: 9.8, matches: 13, runs: 326, wickets: 10, image_initials: 'AR' },
  { name: 'Rinku Singh', team: 'KKR', role: 'Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 162.4, economy: null, matches: 14, runs: 428, wickets: 0, image_initials: 'RiS' },
  { name: 'Varun Chakravarthy', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.2, matches: 14, runs: 0, wickets: 21, image_initials: 'VC' },
  { name: 'Mitchell Starc', team: 'KKR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 12, runs: 0, wickets: 17, image_initials: 'MSt' },
  { name: 'Sanju Samson', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 152.4, economy: null, matches: 14, runs: 478, wickets: 0, image_initials: 'SS' },
  { name: 'Jos Buttler', team: 'RR', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 148.6, economy: null, matches: 13, runs: 510, wickets: 0, image_initials: 'JBu' },
  { name: 'Yuzvendra Chahal', team: 'RR', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.8, matches: 14, runs: 0, wickets: 20, image_initials: 'YC' },
  { name: 'Shimron Hetmyer', team: 'RR', role: 'Batsman', base_price: 2, batting_avg: 34.6, strike_rate: 162.8, economy: null, matches: 12, runs: 346, wickets: 0, image_initials: 'SH' },
  { name: 'David Warner', team: 'DC', role: 'Batsman', base_price: 2, batting_avg: 38.4, strike_rate: 144.2, economy: null, matches: 14, runs: 498, wickets: 0, image_initials: 'DW' },
  { name: 'Rishabh Pant', team: 'DC', role: 'WK-Batsman', base_price: 2, batting_avg: 36.2, strike_rate: 148.6, economy: null, matches: 14, runs: 446, wickets: 0, image_initials: 'RP' },
  { name: 'Axar Patel', team: 'DC', role: 'All-Rounder', base_price: 2, batting_avg: 24.8, strike_rate: 148.4, economy: 7.6, matches: 14, runs: 298, wickets: 13, image_initials: 'AP' },
  { name: 'Anrich Nortje', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.6, matches: 13, runs: 0, wickets: 18, image_initials: 'AN' },
  { name: 'Kuldeep Yadav', team: 'DC', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.4, matches: 14, runs: 0, wickets: 22, image_initials: 'KY' },
  { name: 'Shikhar Dhawan', team: 'PBKS', role: 'Batsman', base_price: 2, batting_avg: 34.8, strike_rate: 128.4, economy: null, matches: 13, runs: 418, wickets: 0, image_initials: 'ShD' },
  { name: 'Liam Livingstone', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 36.4, strike_rate: 164.8, economy: 9.2, matches: 14, runs: 420, wickets: 10, image_initials: 'LL' },
  { name: 'Arshdeep Singh', team: 'PBKS', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.8, matches: 14, runs: 0, wickets: 18, image_initials: 'AS' },
  { name: 'Sam Curran', team: 'PBKS', role: 'All-Rounder', base_price: 2, batting_avg: 22.6, strike_rate: 142.8, economy: 9.4, matches: 12, runs: 226, wickets: 11, image_initials: 'SC' },
  { name: 'Heinrich Klaasen', team: 'SRH', role: 'WK-Batsman', base_price: 2, batting_avg: 42.8, strike_rate: 178.4, economy: null, matches: 14, runs: 542, wickets: 0, image_initials: 'HK' },
  { name: 'Travis Head', team: 'SRH', role: 'Batsman', base_price: 2, batting_avg: 44.6, strike_rate: 180.2, economy: null, matches: 14, runs: 568, wickets: 0, image_initials: 'TH' },
  { name: 'Pat Cummins', team: 'SRH', role: 'All-Rounder', base_price: 2, batting_avg: 22.4, strike_rate: 138.6, economy: 9.2, matches: 14, runs: 224, wickets: 14, image_initials: 'PC' },
  { name: 'Bhuvneshwar Kumar', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.2, matches: 13, runs: 0, wickets: 16, image_initials: 'BK' },
  { name: 'T Natarajan', team: 'SRH', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.4, matches: 14, runs: 0, wickets: 17, image_initials: 'TN' },
  { name: 'Shubman Gill', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 46.2, strike_rate: 136.4, economy: null, matches: 14, runs: 590, wickets: 0, image_initials: 'SG' },
  { name: 'Rashid Khan', team: 'GT', role: 'All-Rounder', base_price: 2, batting_avg: 18.4, strike_rate: 148.6, economy: 6.8, matches: 14, runs: 184, wickets: 20, image_initials: 'RK' },
  { name: 'Mohammed Shami', team: 'GT', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 8.4, matches: 13, runs: 0, wickets: 19, image_initials: 'MoS' },
  { name: 'David Miller', team: 'GT', role: 'Batsman', base_price: 2, batting_avg: 38.6, strike_rate: 158.4, economy: null, matches: 14, runs: 386, wickets: 0, image_initials: 'DM' },
  { name: 'KL Rahul', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 42.4, strike_rate: 136.8, economy: null, matches: 14, runs: 548, wickets: 0, image_initials: 'KLR' },
  { name: 'Nicholas Pooran', team: 'LSG', role: 'WK-Batsman', base_price: 2, batting_avg: 36.8, strike_rate: 164.2, economy: null, matches: 14, runs: 442, wickets: 0, image_initials: 'NP' },
  { name: 'Ravi Bishnoi', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 7.6, matches: 14, runs: 0, wickets: 18, image_initials: 'RB' },
  { name: 'Mark Wood', team: 'LSG', role: 'Bowler', base_price: 2, batting_avg: null, strike_rate: null, economy: 9.2, matches: 12, runs: 0, wickets: 16, image_initials: 'MaW' },
  { name: 'Krunal Pandya', team: 'LSG', role: 'All-Rounder', base_price: 2, batting_avg: 24.6, strike_rate: 138.4, economy: 8.4, matches: 14, runs: 246, wickets: 12, image_initials: 'KrP' },
]

export const TEAM_COLORS = {
  MI: { bg: '#004BA0', text: '#FFFFFF', accent: '#00BFFF' },
  CSK: { bg: '#F5A623', text: '#0B1E3D', accent: '#FDD835' },
  RCB: { bg: '#C8102E', text: '#FFFFFF', accent: '#FFD700' },
  KKR: { bg: '#3A225D', text: '#FFD700', accent: '#FFD700' },
  RR: { bg: '#EA1A85', text: '#FFFFFF', accent: '#29ABE2' },
  DC: { bg: '#0078BC', text: '#FFFFFF', accent: '#EF1C25' },
  PBKS: { bg: '#ED1B24', text: '#FFFFFF', accent: '#A7A9AC' },
  SRH: { bg: '#FF822A', text: '#FFFFFF', accent: '#000000' },
  GT: { bg: '#1C1C5E', text: '#FFFFFF', accent: '#0ABFBC' },
  LSG: { bg: '#A72056', text: '#FFFFFF', accent: '#00B4D8' },
}